version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claro
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
